import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavigationBar from "./components/NavigationBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "ktman blog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const navigationLinks = [
    { linkUrl: "/", linkTitle: "Home" },
    { linkUrl: "/blog", linkTitle: "Blog" },
    { linkUrl: "/resume", linkTitle: "Resume" },
  ];

  return (
    <html lang="en">
      <body className={inter.className}>
        <NavigationBar links={navigationLinks}></NavigationBar>
        {children}
      </body>
    </html>
  );
}
